apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
        aadpodidbinding: identity
    spec:
      containers:
      - name: identity
        image: dotneteconomy.azurecr.io/dotnet.identity:1.0.10
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: dotneteconomy
          - name: IdentitySettings__PathBase
            value: /identity-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5004
        livenessProbe:
          httpGet:
            port: 5004
            path: /health/live
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            port: 5004
            path: /health/ready
          initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP #Default type for Kubernetes
  selector:
    app: identity
  ports:
  - port: 80
    targetPort: 5004
