microserviceName: "identity"

image:
  repository: dotneteconomy.azurecr.io/dotnet.identity
  tag: 1.0.11

envVariables:
  IdentitySettings__PathBase: /identity-svc
  IdentitySettings__CertificateCerFilePath: "/certificates/certificate.crt"
  IdentitySettings__CertificateKeyFilePath: "/certificates/certificate.key"
  IdentityServerSettings__Clients__1__RedirectUris__0: https://dotneteconomy.eastus.cloudapp.azure.com/authentication/login-callback
  IdentityServerSettings__Clients__1__PostLogoutRedirectUris__0: https://dotneteconomy.eastus.cloudapp.azure.com/authentication/logout-callback

container:
  port: 5004
  volumeMounts:
    - name: certificate-volume
      mountPath: /certificates

volumes:
  - name: certificate-volume
    secret:
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

certificate:
  secretName: signing-cert
  hostname: dotneteconomy.eastus.cloudapp.azure.com
